### ISSUE TITLE
Script throws an "Unexpected token" error and refuses to work

### ISSUE THREAD

**Issue by ProudlyTM** [Lee182/budgie-launcher-super#1]
I tried to use the script, but it won't work properly. Here's the full error:

> max@Max-PC:~$ budgie-launcher-super 1
(node:10101) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token )
    at Function (<anonymous>)
    at getPinned (/usr/local/lib/node_modules/budgie-launcher-super/index.js:30:18)
    at <anonymous>
(node:10101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Lee182** [comment]
Thanks for reporting. Question do you have dconf installed on your machine. and if so what does the path `com/solus-project/budgie-panel/instance/icon-tasklist` looklike.  it is effectively going through an eval to convert it to an array

```js
['chromium.desktop', 'visual-studio-code.desktop', 'firefox.desktop', 'mailspring.desktop', 'GitKraken.desktop', 'org.gnome.Nautilus.desktop']
```
I'll change this to JSON.parse and split the replace the quotes

**Comment by ProudlyTM** [comment]
I do have dconf. But when I navigate to the budgie-panel directory, I can only go so far to the "instance" folder. The "icon-tasklist" entry/folder is nowhere to be found:

![image](https://user-images.githubusercontent.com/10185288/46567344-4fdd7600-c93a-11e8-9584-224f03b6e099.png)

![image](https://user-images.githubusercontent.com/10185288/46567390-f6297b80-c93a-11e8-9332-020bf14c8104.png)

**Comment by ProudlyTM** [comment]
Never mind, I fixed it. It seems to work fine now. Good job with the project!
